### ISSUE TITLE
Trackmate tracker paths have changed

### ISSUE THREAD

**Issue by Manon-exp** [paucabar/TrackMate-StarDist_Headless#1]
Hello, it looks like some of the imports from the scripts don't work anymore - the three imports fiji.plugin.trackmate.tracking.LAPUtils, fiji.plugin.trackmate.tracking.sparselap.sparseLAPTrackerFactory and inra.ijpb.plugins.AnalyzeRegions3D. 

From a comment on image.sc I thought maybe this is due to some recent updates in Trackmate? 
https://forum.image.sc/t/cannot-run-imagej-trackmate-by-scripting-failed-to-import-sparselaptrackerfactory/79054/

Thank you for sharing the code!

**Comment by paucabar** [comment]
Hi @Manon-exp ,
Thanks for reporting the issue.
I have reviewed all the scripts and updated when necessary.
Please note that you will need to add the `IJPB-plugins` update site (as explained [here](https://imagej.net/plugins/morpholibj#installation)) in order to use `AnalyzeRegions3D`.
You should be able to use the scripts in this repo after that.
Best wishes
